/**
 * Token Statistics Repository
 *
 * Handles queries for input/output token metrics.
 */

import { Collections, getCollection, QUERY_MAX_TIME_MS } from "../connection";
import type {
	DateRange,
	MessageStatsResult,
	PeriodComparison,
	TokenCountResult,
} from "../types";

/**
 * Get input and output token counts with period comparison
 *
 * Uses the `transactions` collection which tracks the actual tokens consumed by LLM API calls.
 * This is the accurate source because:
 * - tokenType: 'prompt' = Total input tokens sent to the LLM (includes full conversation context)
 * - tokenType: 'completion' = Output tokens generated by the LLM
 * - rawAmount: The token count (stored as negative for spending, so we use $abs)
 *
 * Note: The `messages.tokenCount` field only counts tokens in individual messages,
 * not the full context sent to the LLM which includes all previous conversation messages.
 * The transactions collection records what was actually billed/consumed.
 */
export async function getTokenCounts(
	params: PeriodComparison,
): Promise<TokenCountResult[]> {
	const { startDate, endDate, prevStart, prevEnd } = params;
	const collection = await getCollection(Collections.TRANSACTIONS);

	// DocumentDB does not support $facet — run four parallel aggregations instead
	const sumAbsRawAmount = [
		{ $group: { _id: null, total: { $sum: { $abs: "$rawAmount" } } } },
	];

	const [
		currentInputResult,
		prevInputResult,
		currentOutputResult,
		prevOutputResult,
	] = await Promise.all([
		collection
			.aggregate<{ total: number }>(
				[
					{
						$match: {
							createdAt: { $gte: startDate, $lte: endDate },
							tokenType: "prompt",
						},
					},
					...sumAbsRawAmount,
				],
				{ maxTimeMS: QUERY_MAX_TIME_MS },
			)
			.toArray(),
		collection
			.aggregate<{ total: number }>(
				[
					{
						$match: {
							createdAt: { $gte: prevStart, $lte: prevEnd },
							tokenType: "prompt",
						},
					},
					...sumAbsRawAmount,
				],
				{ maxTimeMS: QUERY_MAX_TIME_MS },
			)
			.toArray(),
		collection
			.aggregate<{ total: number }>(
				[
					{
						$match: {
							createdAt: { $gte: startDate, $lte: endDate },
							tokenType: "completion",
						},
					},
					...sumAbsRawAmount,
				],
				{ maxTimeMS: QUERY_MAX_TIME_MS },
			)
			.toArray(),
		collection
			.aggregate<{ total: number }>(
				[
					{
						$match: {
							createdAt: { $gte: prevStart, $lte: prevEnd },
							tokenType: "completion",
						},
					},
					...sumAbsRawAmount,
				],
				{ maxTimeMS: QUERY_MAX_TIME_MS },
			)
			.toArray(),
	]);

	return [
		{
			currentInputToken: currentInputResult[0]?.total ?? 0,
			currentOutputToken: currentOutputResult[0]?.total ?? 0,
			prevInputToken: prevInputResult[0]?.total ?? 0,
			prevOutputToken: prevOutputResult[0]?.total ?? 0,
		},
	];
}

/**
 * Get average statistics per message with period comparison
 */
export async function getMessageStats(
	params: PeriodComparison,
): Promise<MessageStatsResult[]> {
	const { startDate, endDate, prevStart, prevEnd } = params;
	const collection = await getCollection(Collections.MESSAGES);

	// DocumentDB does not support $facet — run two parallel aggregations instead
	const msgGroupStages = [
		{
			$group: {
				_id: null,
				totalMessages: { $sum: 1 },
				totalTokenCount: { $sum: "$tokenCount" },
				totalSummaryTokenCount: { $sum: "$summaryTokenCount" },
			},
		},
	];

	const [currentResult, prevResult] = await Promise.all([
		collection
			.aggregate<{
				totalMessages: number;
				totalTokenCount: number;
				totalSummaryTokenCount: number;
			}>(
				[
					{ $match: { createdAt: { $gte: startDate, $lte: endDate } } },
					...msgGroupStages,
				],
				{ maxTimeMS: QUERY_MAX_TIME_MS },
			)
			.toArray(),
		collection
			.aggregate<{
				totalMessages: number;
				totalTokenCount: number;
				totalSummaryTokenCount: number;
			}>(
				[
					{ $match: { createdAt: { $gte: prevStart, $lte: prevEnd } } },
					...msgGroupStages,
				],
				{ maxTimeMS: QUERY_MAX_TIME_MS },
			)
			.toArray(),
	]);

	const cur = currentResult[0];
	const prev = prevResult[0];

	return [
		{
			totalMessages: cur?.totalMessages ?? 0,
			totalTokenCount: cur?.totalTokenCount ?? 0,
			totalSummaryTokenCount: cur?.totalSummaryTokenCount ?? 0,
			prevTotalMessages: prev?.totalMessages ?? 0,
			prevTotalTokenCount: prev?.totalTokenCount ?? 0,
			prevTotalSummaryTokenCount: prev?.totalSummaryTokenCount ?? 0,
		},
	];
}

/**
 * Get request heatmap data (requests grouped by day of week and hour)
 */
export async function getRequestHeatmap(
	params: DateRange & { timezone?: string },
) {
	const { startDate, endDate, timezone = "UTC" } = params;
	const collection = await getCollection(Collections.MESSAGES);

	const pipeline = [
		{ $match: { createdAt: { $gte: startDate, $lte: endDate } } },
		{
			$project: {
				// Use hour directly (0-23) instead of 3-hour blocks
				// Use passed timezone for correct local time display
				hour: { $hour: { date: "$createdAt", timezone: timezone } },
				dayOfWeek: {
					$isoDayOfWeek: { date: "$createdAt", timezone: timezone },
				},
				date: {
					$dateToString: {
						format: "%Y-%m-%d",
						date: "$createdAt",
						timezone: timezone,
					},
				},
			},
		},
		{
			$group: {
				_id: { hour: "$hour", dayOfWeek: "$dayOfWeek", date: "$date" },
				totalRequests: { $sum: 1 },
			},
		},
		{ $sort: { "_id.date": 1, "_id.hour": 1 } },
		{
			$project: {
				_id: 0,
				dayOfWeek: "$_id.dayOfWeek",
				timeSlot: "$_id.hour",
				date: "$_id.date",
				totalRequests: 1,
			},
		},
	];

	return collection
		.aggregate(pipeline, { maxTimeMS: QUERY_MAX_TIME_MS })
		.toArray();
}
